open-rmf/rmf_traffic

- rmf_traffic/CHANGELOG.rst
- rmf_traffic/include/rmf_traffic/agv/LaneClosure.hpp
- rmf_traffic/include/rmf_traffic/agv/Planner.hpp
- rmf_traffic/src/rmf_traffic/agv/LaneClosure.cpp
- rmf_traffic/src/rmf_traffic/agv/Planner.cpp
- rmf_traffic/src/rmf_traffic/agv/internal_Planner.hpp
- rmf_traffic/src/rmf_traffic/agv/planning/DifferentialDriveHeuristic.cpp
- rmf_traffic/src/rmf_traffic/agv/planning/DifferentialDriveMap.hpp
- rmf_traffic/src/rmf_traffic/agv/planning/DifferentialDrivePlanner.cpp
- rmf_traffic/src/rmf_traffic/agv/planning/ShortestPathHeuristic.cpp
- rmf_traffic/src/rmf_traffic/agv/planning/Supergraph.cpp
- rmf_traffic/src/rmf_traffic/agv/planning/Supergraph.hpp
- rmf_traffic/test/unit/agv/planning/test_DifferentialDriveHeuristic.cpp
- rmf_traffic/test/unit/agv/planning/test_EuclideanHeuristic.cpp
- rmf_traffic/test/unit/agv/planning/test_ShortestPathHeuristic.cpp
- rmf_traffic/test/unit/agv/planning/test_Supergraph.cpp
- rmf_traffic/test/unit/agv/planning/test_TranslationHeuristic.cpp
- rmf_traffic/test/unit/agv/test_LaneClosure.cpp
- rmf_traffic/test/unit/agv/test_Planner.cpp
This adds a class to track what lanes in a navigation graph are open or closed. Lane closure information is also included in the `rmf_traffic::agv::Planner::Configuration` information, and the planner will refuse to expand down any lane that is closed (except for the start expansion).
> Lane closure

- rmf_traffic/src/rmf_traffic/schedule/Negotiation.cpp
If a negotiation submission is an empty itinerary (which is legal) then there will not be any initial or final endpoint to insert into the negotiation table for that submission. Previously we assumed that the endpoints would always exist, and that could result in a segfault. This PR simply fixes that assumption and checks before inserting them.
> Check if an endpoint is available before inserting it

- rmf_traffic/CHANGELOG.rst
- rmf_traffic/include/rmf_traffic/schedule/Mirror.hpp
- rmf_traffic/include/rmf_traffic/schedule/Patch.hpp
- rmf_traffic/include/rmf_traffic/schedule/Rectifier.hpp
- rmf_traffic/include/rmf_traffic/schedule/Writer.hpp
- rmf_traffic/src/rmf_traffic/schedule/Database.cpp
- rmf_traffic/src/rmf_traffic/schedule/Mirror.cpp
- rmf_traffic/src/rmf_traffic/schedule/Patch.cpp
- rmf_traffic/src/rmf_traffic/schedule/Rectifier.cpp
- rmf_traffic/src/rmf_traffic/schedule/debug_Database.hpp
- rmf_traffic/src/rmf_traffic/schedule/internal_Database.hpp
- rmf_traffic/test/unit/schedule/test_Mirror.cpp
- rmf_traffic/test/unit/schedule/test_Participant.cpp
- rmf_traffic/test/unit/schedule/utils_Database.hpp
Now it is possible for a schedule Mirror to fork off a new schedule Database whose state will match the version of the upstream Database that the Mirror is synced with.
> Allow a Database to be forked off of a Mirror

- rmf_traffic/include/rmf_traffic/agv/debug/debug_Planner.hpp
- rmf_traffic/src/rmf_traffic/agv/planning/DifferentialDrivePlanner.cpp
When a long-lasting obstacle blocks the robot's optimal path, the planner may experience some explosions in the node count while searching for an alternative. This explosion contains many many unhelpful nodes, which this PR will prune out of the search.
Now before expanding a search node, the planner will check if any other search node has already been expanded from that same state within some discrete time window (e.g. 5 seconds). If another search node was already expanded within the discrete time window, then the node that's being considered for expansion will be discarded.
> Prune redundant nodes from the search

- .github/workflows/asan.yaml
- .github/workflows/tsan.yaml
Signed-off-by: Aaron Chong <aaronchongth@gmail.com>
* Removed `push` trigger for `tsan` and `asan` workflow
> Removed push trigger from asan and tsan workflow

- rmf_traffic/include/rmf_traffic/debug/Plumber.hpp
- rmf_traffic/package.xml
- rmf_traffic/src/rmf_traffic/agv/internal_planning.cpp
- rmf_traffic/src/rmf_traffic/agv/internal_planning.hpp
- rmf_traffic/src/rmf_traffic/agv/planning/DifferentialDriveHeuristic.cpp
- rmf_traffic/src/rmf_traffic/agv/planning/DifferentialDriveHeuristic.hpp
- rmf_traffic/src/rmf_traffic/blockade/Participant.cpp
- rmf_traffic/src/rmf_traffic/blockade/Rectifier.cpp
- rmf_traffic/src/rmf_traffic/blockade/internal_Participant.hpp
- rmf_traffic/src/rmf_traffic/blockade/internal_Rectifier.hpp
- rmf_traffic/src/rmf_traffic/schedule/Participant.cpp
- rmf_traffic/src/rmf_traffic/schedule/Rectifier.cpp
- rmf_traffic/src/rmf_traffic/schedule/RectifierInternal.hpp
- rmf_traffic/src/rmf_traffic/schedule/Timeline.hpp
- rmf_traffic/src/rmf_traffic/schedule/internal_Participant.hpp
- rmf_traffic/src/rmf_traffic/schedule/internal_Rectifier.hpp
For multi-threaded use cases, there is a marginal risk that a participant may be destructing at the same time that a rectifier asks it to verify the current state of the database. That race condition can take place even if the ordinary read/write operations on the participant object are tightly controlled, because it can be quite difficult to control when and where (i.e. on which thread) the participant ends up getting destructed.
This PR tweaks the implementation of the participant class so that its internal state is managed by a `std::shared_ptr` which will ensure it does not begin destructing while the rectifier is operating on it.
There are also a few other unrelated memory initialization fixes that are snuck in here.
> Fix participant lifecycles

- rmf_traffic/include/rmf_traffic/agv/RouteValidator.hpp
- rmf_traffic/include/rmf_traffic/schedule/StubbornNegotiator.hpp
- rmf_traffic/src/rmf_traffic/agv/RouteValidator.cpp
- rmf_traffic/src/rmf_traffic/schedule/StubbornNegotiator.cpp
The `StubbornNegotiator` negotiation strategy may be too rigid to be a good fit for some tricky circumstances. This PR provides more knobs to tailor the strategy of a `StubbornNegotiator` to better suit various circumstances.
These changes are particularly important if multiple read-only traffic participants need to co-exist in the same space. The new stubborn negotiation options allows conflicts between read-only participants to be resolved outside of RMF (e.g. by human operators) while still resolving any conflicts between the read-only and autonomous participants.
> Make the stubborn negotiator's strategy more flexible

- rmf_traffic/CHANGELOG.md
- rmf_traffic/include/rmf_traffic/agv/Graph.hpp
- rmf_traffic/src/rmf_traffic/agv/Graph.cpp
- rmf_traffic/src/rmf_traffic/agv/planning/Supergraph.cpp
- rmf_traffic/test/unit/agv/test_Planner.cpp
This PR introduces the ability to (optionally) set speed limits on nav graph lanes. These speed limits will be respected by the planner.
For the initial implementation if there are multiple speed limits along one continuous stretch (collinear lanes that have different speed limits), then the planner will use the lowest speed limit along the entire stretch (or possibly come to a stop at the point where the lanes change and then switch speeds, if that would be faster). This approach does not provide optimal trajectories. We should instead have the robot accelerate/decelerate at each lane intersection in compliance with the changes in speed limits, but that will take considerably more effort to work out, so we'll start with this and improve the implementation in a future PR.
> Add lane speed limits to the graph and factor them into the planning

- rmf_traffic/include/rmf_traffic/agv/Planner.hpp
- rmf_traffic/src/rmf_traffic/agv/Planner.cpp
- rmf_traffic/test/unit/agv/test_Planner.cpp
- rmf_traffic/thirdparty/fcl/include/fcl/geometry/shape/sphere-inl.h
- rmf_traffic/thirdparty/fcl/include/fcl/geometry/shape/sphere.h
As reported in https://github.com/open-rmf/rmf_ros2/issues/82, Thread Sanitizer is complaining about certain data races that are happening on `rmf_traffic` data structures.
So far these data races have not had an observable impact, and are probably harmless, but this PR switches us over to using best practices anyway.
> Use std::atomic_bool for safe synchronization

- rmf_traffic/CMakeLists.txt
The CMake user package registry can cause unexpected behavior if people aren't accustomed to it. This PR removes the `export(PACKAGE ...)` invocation that adds to the user package registry in `~/.cmake/packages` during the `colcon` build/install process.
Signed-off-by: Morgan Quigley <morgan@osrfoundation.org>
> the CMake user package registry can do unexpected things.

- rmf_traffic/CMakeLists.txt
- rmf_traffic/package.xml
We currently have the rmf_cmake_uncrustify package that is used for style checking with colcon test. The original reason for having this package and not using ament_cmake_uncrustify was that the latter did not support custom uncrustify configuration files. But this feature was [merged upstream](https://github.com/ament/ament_lint/pull/200) quite a while ago and has been part of `foxy` and `galactic` releases. Hence, switching back to `ament_cmake_uncrustify` for ease of maintenance and distribution.
> Use ament_cmake_uncrustify

- rmf_traffic/include/rmf_traffic/agv/Graph.hpp
- rmf_traffic/src/rmf_traffic/agv/Graph.cpp
We often need to print out (or stringify) the names of waypoints, including waypoints that do not have a designated name. Every place where we need to do this, we have to write custom logic for deciding whether to print the name of the waypoint or whether to stringify its graph index with some extra formatting.
This PR provides a utility to make this process simpler and avoid rewriting this same logic over and over in each place that it's needed.
> Provide a utility for generating waypoint names

- rmf_traffic/CMakeLists.txt
- rmf_traffic/include/rmf_traffic/Profile.hpp
- rmf_traffic/include/rmf_traffic/schedule/ParticipantDescription.hpp
- rmf_traffic/include/rmf_traffic/schedule/Rectifier.hpp
- rmf_traffic/src/rmf_traffic/Profile.cpp
- rmf_traffic/src/rmf_traffic/geometry/ShapeInternal.hpp
- rmf_traffic/src/rmf_traffic/schedule/Participant.cpp
- rmf_traffic/src/rmf_traffic/schedule/ParticipantDescription.cpp
- rmf_traffic/src/rmf_traffic/schedule/Rectifier.cpp
- rmf_traffic/src/rmf_traffic/schedule/internal_Participant.hpp
These add some features to the schedule participant rectifier that will allow remote writers to fix discrepancies between their local participants and the remote database's model of them.
This depends on https://github.com/open-rmf/rmf_utils/pull/18 which should be merged first.
> Allow the rectifier to help fix participant ID and description discrepancies

- rmf_traffic/CMakeLists.txt
- rmf_traffic/cmake/rmf_traffic-config.cmake.in
Signed-off-by: Aaron Chong <aaronchongth@gmail.com>
Fixes https://github.com/open-rmf/rmf_traffic/issues/55.
Edit: Apologies for the branch name pattern :man_facepalming: 
Using placeholders in `rmf_traffic/cmake/rmf_traffic-config.cmake.in`, to be generated for `eigen3_cmake_module` only if it is found.
> Using placeholders to add dependency only if the package is found

- rmf_traffic/test/unit/test_Conflict.cpp
- rmf_traffic/thirdparty/fcl/include/fcl/math/motion/spline_motion-inl.h
- rmf_traffic/thirdparty/fcl/include/fcl/math/motion/tbv_motion_bound_visitor-inl.h
- rmf_traffic/thirdparty/fcl/include/fcl/narrowphase/detail/conservative_advancement_func_matrix-inl.h
- rmf_traffic/thirdparty/fcl/include/fcl/narrowphase/detail/traversal/distance/shape_conservative_advancement_traversal_node-inl.h
It seems that the FCL implementation of conservative advancement for two splines has a few bugs in it that allow the conservative advancement algorithm to overshoot. This PR fixes it for the internal version of FCL used by `rmf_traffic`. I'll also be submitting a PR to the upstream FCL to fix it likewise there.
> Fixing bugs in FCL conservative advancement implementation

- rmf_traffic/include/rmf_traffic/agv/Graph.hpp
- rmf_traffic/src/rmf_traffic/agv/Graph.cpp
- rmf_traffic/src/rmf_traffic/agv/internal_Graph.hpp
- rmf_traffic/test/unit/agv/test_Graph.cpp
This PR adds an API for `lanes_into` to `rmf_traffic`
Given a `Graph::Waypoint` there is a function to calculate lanes from it but while the data structure to containing lanes into the waypoint was existing, its content was not exposed to a user API.
This PR just adds the user API to return the lanes into a waypoint, as well as adding a few lines of test code to make sure it's behaving sensibly.
> Add lanes_into API to AGV Graph

- .github/workflows/build.yaml
Signed-off-by: Marco A. Gutierrez <marco@openrobotics.org>
Current github workflow tries to add ROS1 repos on `jammy` and it fails because the Release file it's not there for `jammy`:
`The repository 'http://packages.ros.org/ros/ubuntu jammy Release' does not have a Release file.`
Moving github workflow to _matrix mode_ as suggested in https://github.com/ros-tooling/setup-ros/tree/v0.3#iterating-on-all-ros-distributions-for-all-platforms to ease the build and test of different combinations of ubuntu distros and ros distros.
Currently building and testing on `focal` + `galactic` and `jammy` + `rolling`.
> Using matrix to ease test with different distros

- rmf_traffic/CMakeLists.txt
- rmf_traffic/cmake/rmf_traffic-config.cmake.in
https://github.com/open-rmf/rmf_demos/issues/132 reported that their machine failed to link `rmf_traffic` against pthread. In theory this PR should fix that problem.
> Always link rmf_traffic against the Threads target

- rmf_traffic/src/rmf_traffic/agv/planning/Supergraph.cpp
~~When a negative or zero value is given for the speed limit on a lane, the planner will now print a warning and override the value with 1/1000 of the agent's normal speed. I expect in most cases setting the speed limit to such a small value is likely to achieve what the user wanted, but it is still strongly recommended to use the lane blocking feature in cases where a "zero speed limit" is really wanted.~~
This PR has been updated so that when a negative- or zero-value speed limit is given for a lane, the lane will be treated as if it is closed, but a warning will be printed out about the unhygienic speed limit value.
> Make sure the planner will not use a negative- or zero-value speed limit

- rmf_traffic/CHANGELOG.md
- rmf_traffic/include/rmf_traffic/agv/Planner.hpp
- rmf_traffic/src/rmf_traffic/agv/Planner.cpp
- rmf_traffic/src/rmf_traffic/agv/internal_Planner.hpp
- rmf_traffic/src/rmf_traffic/agv/internal_planning.hpp
- rmf_traffic/src/rmf_traffic/agv/planning/CacheManager.hpp
- rmf_traffic/src/rmf_traffic/agv/planning/DifferentialDriveHeuristic.cpp
- rmf_traffic/src/rmf_traffic/agv/planning/DifferentialDriveHeuristic.hpp
- rmf_traffic/src/rmf_traffic/agv/planning/DifferentialDrivePlanner.cpp
- rmf_traffic/src/rmf_traffic/agv/planning/DifferentialDrivePlanner.hpp
- rmf_traffic/src/rmf_traffic/agv/planning/MinimalTravelHeuristic.cpp
- rmf_traffic/src/rmf_traffic/agv/planning/MinimalTravelHeuristic.hpp
- rmf_traffic/src/rmf_traffic/agv/planning/ShortestPathHeuristic.hpp
- rmf_traffic/src/rmf_traffic/agv/planning/Tree.hpp
- rmf_traffic/src/rmf_traffic/agv/planning/impl_Tree.hpp
- rmf_traffic/test/unit/agv/test_Planner.cpp
This PR adds a quickest_path feature for the planner. Asking for the quickest_path bypasses many of the normal capabilities of the planner to quickly give back an estimate of the quickest path to get between two points.
> Add quickest_path feature to planner

- rmf_traffic/src/rmf_traffic/schedule/Mirror.cpp
Change function returning nullopt to explicitly return empty data structure, when needed.
The get_itinerary function, returning an `std::optional`, was using empty value initialization to return an optional with a value that contains an empty data structure.
It seems this behavior was actually a compiler bug and the actual intended behavior is for `return std::nullopt;` and `return {}` to be equivalent, as can be seen in this [stack overflow thread](https://stackoverflow.com/questions/57964217/stdoptional-construct-empty-with-or-stdnullopt).
In [compile explorer](https://godbolt.org/z/mDeDZQ), it shows that with the latest gcc / clang version the two constructors compile to the same assembly, while in gcc 9 / 10 they compile differently and do value initialization.
This PR changes the …
> Change return from nullopt to empty data structure

- rmf_traffic/src/rmf_traffic/agv/planning/ShortestPathHeuristic.cpp
- rmf_traffic/test/unit/agv/test_Planner.cpp
The quickest path function introduced in #84 was not accounting for closed lanes and was still using them, this PR fixes it (and add a test) so that closed lanes are not used when finding the quickest path to a destination
> Fix quickest path function to account for closed lanes

- rmf_traffic/include/rmf_traffic/schedule/Database.hpp
- rmf_traffic/include/rmf_traffic/schedule/Participant.hpp
- rmf_traffic/src/rmf_traffic/agv/planning/DifferentialDrivePlanner.cpp
- rmf_traffic/src/rmf_traffic/schedule/Database.cpp
- rmf_traffic/src/rmf_traffic/schedule/Participant.cpp
- rmf_traffic/src/rmf_traffic/schedule/internal_Participant.hpp
- rmf_traffic/test/unit/agv/test_Negotiator.cpp
- rmf_traffic/test/unit/schedule/test_Mirror.cpp
- rmf_traffic/test/unit/schedule/test_Participant.cpp
- rmf_traffic/test/unit/schedule/utils_Database.hpp
During intensive long-run testing, it was discovered that bad inputs from schedule participants can lead to harmful behavior in the traffic schedule. This PR helps in two ways
* Excessive cumulative delays for schedule participants trigger the creation of new routes within the timeline storage so that older route information can be safely culled in a reasonable time.
* The Participant API was changed to make it much easier to correctly set the cumulative delay, even in heavily async code.
> Fix culling and delay implementation

- rmf_traffic/CMakeLists.txt
- rmf_traffic/include/rmf_traffic/schedule/Participant.hpp
- rmf_traffic/src/rmf_traffic/schedule/Participant.cpp
- rmf_traffic/src/rmf_traffic/schedule/internal_Participant.hpp
This PR adds an API to `rmf_traffic::schedule::Participant` that allows participants to update their profile on the schedule. This allows the profile to be changed in the database without destructing and recreating the `Participant` object.
> Provide an API for changing participant profile

- .github/workflows/asan.yaml
- .github/workflows/build.yaml
- .github/workflows/tsan.yaml
- rmf_traffic/QUALITY_DECLARATION.md
- rmf_traffic/include/rmf_traffic/Trajectory.hpp
- rmf_traffic/include/rmf_traffic/agv/Graph.hpp
- rmf_traffic/include/rmf_traffic/schedule/Participant.hpp
- rmf_traffic/src/rmf_traffic/Trajectory.cpp
- rmf_traffic/src/rmf_traffic/agv/Graph.cpp
- rmf_traffic/src/rmf_traffic/agv/Planner.cpp
- rmf_traffic/src/rmf_traffic/agv/internal_Graph.hpp
- rmf_traffic/src/rmf_traffic/agv/planning/DifferentialDrivePlanner.cpp
- rmf_traffic/src/rmf_traffic/agv/planning/Supergraph.cpp
- rmf_traffic/src/rmf_traffic/schedule/Database.cpp
- rmf_traffic/src/rmf_traffic/schedule/Participant.cpp
- rmf_traffic/test/unit/schedule/test_Database.cpp
- rmf_traffic/test/unit/schedule/test_Mirror.cpp
This PR introduces a variety of new navigation graph elements and properties used for new features that are being added to `rmf_fleet_adapter`. It also contains a few bug fixes in the planner. A more detailed description will be filled in when this PR comes out of draft status.
> Introducing new graph elements and properties

- rmf_traffic/src/rmf_traffic/agv/planning/DifferentialDrivePlanner.cpp
This PR fixes some undefined behavior that can happen when trying to remove unnecessary motions from a plan. We were accidentally dereferencing an `optional` that may have a `nullopt` value.
> Fix undefined behavior in plan cleanup

- rmf_traffic/include/rmf_traffic/agv/Graph.hpp
- rmf_traffic/src/rmf_traffic/agv/planning/DifferentialDrivePlanner.cpp
- rmf_traffic/test/unit/agv/test_Planner.cpp
This PR targets https://github.com/open-rmf/rmf/issues/556 where in-place rotation commands for certain paths are missing. After tracing the fleet adapter and `rmf_traffic` planner, it seems the planner sometimes fails to provide these waypoints. These in-place rotation waypoints may be essential for AGVs that rely entirely on RMF to align towards their next destination. The fix implemented is to check for such gaps inside `reconstruct_waypoints` and insert the rotation command as needed.
**Test the fix**
The issue can be consistently reproduced in the Office demos world by sending a patrol command for `tinyRobot1` to `hardware_2`. Do set the `skip_rotation_commands` param to `False` when testing.
When the robot is returning from `hardware_2` to its charger, it would provide the following …
> Insert in-place rotation waypoint if missing

- rmf_traffic/src/rmf_traffic/schedule/Database.cpp
- rmf_traffic/src/rmf_traffic/schedule/Mirror.cpp
This should resolve the issue report [here](https://github.com/open-rmf/rmf/discussions/567#discussioncomment-12370285) where a robot waits for an excessive amount of time on a traffic dependency that has already moved out of the way.
The bug occurs when Robot A needs to wait at some point for Robot B to move out of the way, but Robot B has already **_completely finished its route_** before Robot A reaches the waiting point.
This PR detects whether Robot B has already finished its route while creating the dependency subscription, and immediately deprecates the dependency if true. If the robot has not finished its route at the time the dependency subscription is made, then there are other mechanisms that will detect the change and alert the waiting robot.
> Immeidately mark dependencies as deprecated when the target plan was cleared

- rmf_traffic/include/rmf_traffic/agv/Planner.hpp
- rmf_traffic/src/rmf_traffic/agv/Planner.cpp
- rmf_traffic/src/rmf_traffic/agv/internal_Planner.hpp
- rmf_traffic/src/rmf_traffic/agv/internal_planning.hpp
- rmf_traffic/src/rmf_traffic/agv/planning/CacheManager.hpp
- rmf_traffic/src/rmf_traffic/agv/planning/DifferentialDriveHeuristic.cpp
- rmf_traffic/src/rmf_traffic/agv/planning/DifferentialDriveHeuristic.hpp
- rmf_traffic/src/rmf_traffic/agv/planning/DifferentialDrivePlanner.cpp
- rmf_traffic/src/rmf_traffic/agv/planning/DifferentialDrivePlanner.hpp
- rmf_traffic/src/rmf_traffic/agv/planning/Supergraph.hpp
- rmf_traffic/src/rmf_traffic/agv/planning/Tree.hpp
- rmf_traffic/src/rmf_traffic/agv/planning/impl_Tree.hpp
- rmf_traffic/test/unit/agv/planning/test_DifferentialDriveHeuristic.cpp
This PR is being opened in response to https://github.com/open-rmf/rmf/discussions/664#discussioncomment-13070430
The main purpose is to give some rough insight into the memory size of the caches in the traffic planner. However while implementing the mechanism to check their sizes, I noticed an inefficiency: the `ShortestPathHeuristic` was being remade for each different goal search. I took this opportunity to tweak the implementation so that we create one single `ShortestPathHeuristic` instance per planner and use it across all goal searches. This should improve both performance and memory size.
Note that we currently expect the Euclidean cache to say its size is 0 because it's not being used in the current planner implementation. I kept it in there for completeness, in case we do go …
> Add a method to audit the size of planner caches

- rmf_traffic/include/rmf_traffic/agv/Planner.hpp
- rmf_traffic/src/rmf_traffic/agv/Planner.cpp
- rmf_traffic/src/rmf_traffic/agv/internal_planning.hpp
- rmf_traffic/src/rmf_traffic/agv/planning/CacheManager.hpp
- rmf_traffic/src/rmf_traffic/agv/planning/DifferentialDrivePlanner.cpp
- rmf_traffic/src/rmf_traffic/agv/planning/DifferentialDrivePlanner.hpp
Following up on https://github.com/open-rmf/rmf/discussions/664#discussioncomment-13084007 this PR provides an API for clearing out the cache within the planner that tends to grow the largest. This API can be called periodically to help manage inflation of a fleet adapter's memory.
> Add an API for clearing the planner cache

- rmf_traffic/include/rmf_traffic/agv/Planner.hpp
- rmf_traffic/src/rmf_traffic/agv/Planner.cpp
- rmf_traffic/src/rmf_traffic/agv/internal_planning.hpp
- rmf_traffic/src/rmf_traffic/agv/planning/DifferentialDriveHeuristic.cpp
- rmf_traffic/src/rmf_traffic/agv/planning/DifferentialDriveHeuristic.hpp
- rmf_traffic/src/rmf_traffic/agv/planning/DifferentialDrivePlanner.cpp
- rmf_traffic/src/rmf_traffic/agv/planning/DifferentialDrivePlanner.hpp
- rmf_traffic/src/rmf_traffic/agv/planning/Tree.hpp
- rmf_traffic/src/rmf_traffic/agv/planning/impl_Tree.hpp
As a follow up on [https://discourse.openrobotics.org/t/memory-growth-in-fleet-adapter-and-traffic-schedule-664/44530/16](https://discourse.openrobotics.org/t/memory-growth-in-fleet-adapter-and-traffic-schedule-664/44530/16), this PR provides API for clearing planner inner cache.
> Add API to clear planner inner cache

- rmf_traffic/src/rmf_traffic/agv/Planner.cpp
- rmf_traffic/src/rmf_traffic/agv/internal_Planner.hpp
This is a supplemental fix for https://github.com/open-rmf/rmf_ros2/issues/462. The main fix is in https://github.com/open-rmf/rmf_ros2/pull/464, but this PR adds another layer of protection by ensuring that all access to a `Planner::Result` is thread-safe. That way we won't get data races from using `Planner::Result` in `rmf_fleet_adapter`, even if there are data race accesses to `Planner::Result` that we haven't caught yet.
> Embed mutex inside Planner::Result
